# Exported from Render on 2025-07-15T05:40:44Z
databases:
- name: postn8ngrace
  databaseName: postn8ngrace
  user: postn8ngrace_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: n8n:latest
  runtime: image
  image:
    url: docker.io/n8nio/n8n:latest
  plan: free
  envVars:
  - key: N8N_USER_FOLDER
    sync: false
  - key: N8N_PERSONALIZATION_ENABLED
    sync: false
  - key: N8N_PATH
    sync: false
  - key: N8N_EMAIL_MODE
    sync: false
  - key: N8N_EDITOR_BASE_URL
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  - key: N8N_HOST
    sync: false
  - key: N8N_TEMPLATES_ENABLED
    sync: false
  - key: Port
    sync: false
  - fromGroup: n8nenv
  region: oregon
  autoDeployTrigger: commit
- type: keyvalue
  name: webiton-redis-redis
  plan: free
  region: oregon
  maxmemoryPolicy: allkeys-lru
  ipAllowList: []
version: "1"
